// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title DegenBadge
 * @notice A non-transferable Soulbound Token (SBT) representing a user's RoastMyWallet score and classification.
 * @dev Employs off-chain cryptographic signatures to validate scores and scores minting fees.
 */
contract DegenBadge is ERC721URIStorage, Ownable {
    uint256 private _nextTokenId;

    struct BadgeInfo {
        uint256 degenScore;
        string classification;
    }

    // Cost to mint the badge (e.g., 0.0003 ETH ~ $1 at current prices)
    uint256 public mintPrice = 0.0003 ether;

    // Address authorized to sign scores on the backend
    address public authorizedSigner;

    // Maps player address to their badge metadata
    mapping(address => BadgeInfo) public badges;
    // Maps player address to their assigned Token ID
    mapping(address => uint256) public addressToTokenId;

    event BadgeMinted(address indexed player, uint256 tokenId, uint256 degenScore, string classification);
    event BadgeUpdated(address indexed player, uint256 tokenId, uint256 degenScore, string classification);
    event SignerUpdated(address indexed oldSigner, address indexed newSigner);
    event PriceUpdated(uint256 oldPrice, uint256 newPrice);

    constructor(address _authorizedSigner) ERC721("Degen Badge", "DEGEN") Ownable(msg.sender) {
        require(_authorizedSigner != address(0), "DegenBadge: Signer cannot be zero address");
        authorizedSigner = _authorizedSigner;
    }

    /**
     * @notice Mints or updates a Soulbound Degen License Badge for the sender.
     * @dev Validates the backend signature to prevent user falsification of scores.
     */
    function mintBadge(
        uint256 degenScore, 
        string calldata classification, 
        string calldata uri,
        bytes calldata signature
    ) external payable returns (uint256) {
        require(msg.value >= mintPrice, "DegenBadge: Insufficient payment");
        require(degenScore <= 100, "DegenBadge: Maximum score is 100");

        // Verify the cryptographic signature generated by the authorized backend signer
        bytes32 messageHash = keccak256(abi.encodePacked(msg.sender, degenScore, classification, uri));
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);
        address recoveredSigner = ECDSA.recover(ethSignedMessageHash, signature);
        
        require(recoveredSigner == authorizedSigner, "DegenBadge: Invalid signature");

        uint256 tokenId = addressToTokenId[msg.sender];
        
        if (tokenId == 0) {
            // New mint
            _nextTokenId++;
            uint256 newTokenId = _nextTokenId;
            
            _safeMint(msg.sender, newTokenId);
            _setTokenURI(newTokenId, uri);
            
            addressToTokenId[msg.sender] = newTokenId;
            badges[msg.sender] = BadgeInfo(degenScore, classification);
            
            emit BadgeMinted(msg.sender, newTokenId, degenScore, classification);
            return newTokenId;
        } else {
            // Update existing badge stats
            _setTokenURI(tokenId, uri);
            badges[msg.sender] = BadgeInfo(degenScore, classification);
            
            emit BadgeUpdated(msg.sender, tokenId, degenScore, classification);
            return tokenId;
        }
    }

    /**
     * @notice Updates the authorized backend signing address.
     */
    function setAuthorizedSigner(address _authorizedSigner) external onlyOwner {
        require(_authorizedSigner != address(0), "DegenBadge: Signer cannot be zero address");
        emit SignerUpdated(authorizedSigner, _authorizedSigner);
        authorizedSigner = _authorizedSigner;
    }

    /**
     * @notice Updates the mint price.
     */
    function setMintPrice(uint256 _mintPrice) external onlyOwner {
        emit PriceUpdated(mintPrice, _mintPrice);
        mintPrice = _mintPrice;
    }

    /**
     * @notice Withdraws accumulated mint fees from the contract.
     */
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "DegenBadge: Nothing to withdraw");
        
        (bool success, ) = payable(owner()).call{value: balance}("");
        require(success, "DegenBadge: Transfer failed");
    }

    /**
     * @dev Overrides ERC721 _update to block standard transfers, making the tokens Soulbound.
     * Only allows minting (transfer from address(0)) and burning (transfer to address(0)).
     */
    function _update(
        address to, 
        uint256 tokenId, 
        address auth
    ) internal override(ERC721) returns (address) {
        address from = _ownerOf(tokenId);
        
        // Block transfers between non-zero addresses (make it Soulbound)
        if (from != address(0) && to != address(0)) {
            revert("DegenBadge: Soulbound tokens cannot be transferred");
        }
        
        return super._update(to, tokenId, auth);
    }
}
